/* ==========================================================================
   EUROPA 2026 — FUENTE ÚNICA DE VERDAD
   --------------------------------------------------------------------------
   Este es el ÚNICO archivo que debes editar para cambiar el viaje.
   No toques app.js ni styles.css.

   Cómo editar:
     - Cambiar una hora  ->  busca la parada y cambia  t: "11:00"
     - Cambiar un dato   ->  cambia el texto entre comillas
     - Marcar pagado     ->  en RESERVAS, cambia  status: "pagado"
     - Añadir una parada ->  copia un bloque { ... } completo y pégalo
                             en el lugar de la secuencia que le toca

   Marcadores obligatorios (NO los borres si el dato no está verificado):
     pend: ["texto"]   -> se muestra en la app como DATO PENDIENTE
   ========================================================================== */

window.TRIP = {
  name: "EUROPA 2026",
  version: "1.0",
  updated: "2026-09-04",
  travelers: 2,

  /* ---------------------------------------------------------------- CIUDADES */
  cities: [
    { id: "mad", name: "Madrid",    accent: "#A6301F", tz: "Europe/Madrid",
      from: "2026-09-06", to: "2026-09-09",
      hotel: { name: "Quatro Puerta del Sol", addr: "Calle de Sevilla 4, 28014 Madrid",
               lat: 40.4174, lng: -3.7008, phone: "", checkin: "", checkout: "",
               pend: ["Teléfono, hora de check-in y check-out: VERIFICAR EN COMPROBANTE"] },
      info: { emergencias: "112", transporte: "Metro de Madrid · abono turístico o billete sencillo",
              moneda: "Euro (€)", propinas: "No obligatorias. Redondear o 5–10 % si el servicio fue bueno",
              idioma: "Español", horarios: "Comida 14:00–16:00 · cena 21:00–23:00",
              aeropuerto: "Madrid-Barajas Adolfo Suárez · Terminal 4" } },

    { id: "sto", name: "Estocolmo", accent: "#1E6B8C", tz: "Europe/Stockholm",
      from: "2026-09-09", to: "2026-09-12",
      hotel: { name: "Hotel C Stockholm", addr: "Vasaplan 4, 111 20 Estocolmo",
               lat: 59.3315, lng: 18.0585, phone: "", checkin: "", checkout: "",
               pend: ["Teléfono y horas de check-in/out: VERIFICAR EN COMPROBANTE"] },
      info: { emergencias: "112", transporte: "SL · tarjeta bancaria contactless directamente en el torniquete",
              moneda: "Corona sueca (SEK). Prácticamente todo con tarjeta, casi nadie acepta efectivo",
              propinas: "No se esperan. El servicio va incluido",
              idioma: "Sueco. Inglés universal",
              horarios: "Cena temprana: 18:00–20:00. Muchos cafés cierran 17:00–18:00",
              aeropuerto: "Estocolmo-Arlanda (ARN)" } },

    { id: "par", name: "París",     accent: "#3E4A78", tz: "Europe/Paris",
      from: "2026-09-12", to: "2026-09-18",
      hotel: { name: "Meliá Paris Vendôme", addr: "8 Rue Cambon, 75001 París",
               lat: 48.8664, lng: 2.3268, phone: "+33 1 44 77 54 00", checkin: "15:00", checkout: "12:00",
               note: "1er distrito, entre Place Vendôme y Place de la Concorde. Metro Concorde a 300 m; Tullerías y Louvre a pie.",
               pend: ["Coordenadas aproximadas: verificar en Maps"] },
      info: { emergencias: "112", transporte: "Metro y RER · Navigo Easy o billete t+ ",
              moneda: "Euro (€)", propinas: "Servicio incluido. Redondear si acaso",
              idioma: "Francés. Saludar siempre con «Bonjour» al entrar",
              horarios: "Comida 12:00–14:00 · cena 19:30–22:00",
              aeropuerto: "París-Charles de Gaulle (CDG)" } }
  ],

  /* ------------------------------------------------------------------ VUELOS */
  flights: [
    { id: "f0", date: "2026-09-05", airline: "", number: "",
      from: "Mérida (MID)", to: "Madrid-Barajas (MAD)",
      dep: "13:30", arr: "15:00", arrDate: "2026-09-06",
      terminalOut: "", terminalIn: "",
      pend: ["Aerolínea, número de vuelo y terminales: VERIFICAR EN COMPROBANTE"] },

    { id: "f1", date: "2026-09-09", airline: "Iberia", number: "IB823",
      from: "Madrid-Barajas (MAD)", to: "Estocolmo-Arlanda (ARN)",
      dep: "10:15", arr: "14:10", terminalOut: "T4", terminalIn: "",
      bag: "Mano 3 kg · documentada 23 kg (tarifa Óptima)",
      note: "Comprado por PriceTravel. Tarifa no reembolsable." },

    { id: "f2", date: "2026-09-12", airline: "SAS", number: "SK579",
      from: "Estocolmo-Arlanda (ARN)", to: "París-Charles de Gaulle (CDG)",
      dep: "17:50", arr: "20:25", terminalOut: "", terminalIn: "",
      bag: "1 carry-on hasta 8 kg / 118 cm + 1 documentada hasta 23 kg por persona" },

    { id: "f3", date: "2026-09-18", airline: "", number: "",
      from: "París-Charles de Gaulle (CDG)", to: "Mérida (MID)",
      dep: "10:00", arr: "", terminalOut: "", terminalIn: "",
      pend: ["HORA PROVISIONAL: 10:00 dicho de memoria, sin comprobante. Confirmar con el boleto.",
             "Aerolínea, número de vuelo, escalas y terminal: DATO PENDIENTE"] }
  ],

  /* ---------------------------------------------------------------- RESERVAS */
  reservations: [
    { id: "r_palacio",  name: "Palacio Real de Madrid · visita guiada", city: "mad",
      date: "2026-09-07", time: "11:00", people: 2, status: "confirmado",
      provider: "", code: "", meeting: "VERIFICAR EN COMPROBANTE",
      addr: "Calle de Bailén s/n, 28071 Madrid" },

    { id: "r_labola",   name: "La Bola · cocido madrileño", city: "mad",
      date: "2026-09-07", time: "13:30", people: 2, status: "confirmado",
      provider: "Restaurante La Bola", code: "", addr: "Calle de la Bola 5, 28013 Madrid" },

    { id: "r_cardamomo", name: "Cardamomo · tablao flamenco", city: "mad",
      date: "2026-09-07", time: "", people: 2, status: "confirmado",
      provider: "Cardamomo", code: "", addr: "Calle de Echegaray 15, 28014 Madrid",
      pend: ["Hora exacta del espectáculo: VERIFICAR EN COMPROBANTE"] },

    { id: "r_prado",    name: "Museo Nacional del Prado", city: "mad",
      date: "2026-09-08", time: "12:00", people: 2, status: "confirmado",
      provider: "", code: "", addr: "Calle de Ruiz de Alarcón 23, 28014 Madrid" },

    { id: "r_icebar",   name: "ICEBAR Stockholm", city: "sto",
      date: "2026-09-09", time: "21:00", people: 2, status: "pendiente",
      provider: "ICEBAR by Hotel C", addr: "Vasaplan 4, Estocolmo",
      note: "Aprobado como actividad. No consta reservado." },

    { id: "r_fx",       name: "Visita a la fábrica FX Airguns · Mariestad", city: "sto",
      date: "2026-09-10", time: "11:00", people: 4, status: "confirmado",
      provider: "FX Airguns", addr: "Mariestad, Suecia",
      pend: ["Dirección exacta de la fábrica y persona de contacto: DATO PENDIENTE"] },

    { id: "r_freesto",  name: "Free tour por Estocolmo (español)", city: "sto",
      date: "2026-09-11", time: "13:00", people: 4, status: "confirmado",
      provider: "Civitatis (verificar en el correo de confirmación)", code: "A41038311",
      meeting: "Plaza Gustav Adolf (Gustav Adolfs torg)",
      note: "13:00 h · 2 h 30 · gratis con propina. Termina en Stortorget. SON 4 PERSONAS: el amigo se suma este día.",
      pend: ["Punto exacto dentro de la plaza y referencia visual del guía: VERIFICAR EN COMPROBANTE"] },

    { id: "r_crucerosto", name: "Crucero por el archipiélago · Strömma", city: "sto",
      date: "2026-09-12", time: "10:30", people: 2, status: "pendiente",
      provider: "Strömma", meeting: "Strandvägen, MUELLE 15",
      note: "10:30–13:00 · 2 h 30 · barco M/S Östanå I. ~SEK 375/persona.",
      pend: ["No consta reservado. Confirmar antes de viajar."] },

    { id: "r_freearco", name: "Free tour Arco del Triunfo y Campos Elíseos (español)", city: "par",
      date: "2026-09-13", time: "16:30", people: 2, status: "confirmado",
      provider: "Civitatis (verificar en el correo de confirmación)", code: "A41342195",
      meeting: "VERIFICAR EN COMPROBANTE",
      note: "Termina en la zona de Trocadéro.",
      pend: ["Punto exacto de encuentro y referencia visual del guía: VERIFICAR EN COMPROBANTE"] },

    { id: "r_bateaux",  name: "Bateaux Parisiens · crucero por el Sena", city: "par",
      date: "2026-09-13", time: "20:00", people: 2, status: "pagado",
      provider: "Bateaux Parisiens", meeting: "Port de la Bourdonnais, 75007 París",
      note: "Boleto de horario abierto (Sightseeing Online Exclusive). El horario de las 19:00 no cabe después del free tour: se fijó el Plan B de las 20:00 como principal. Atardecer ~20:07, visible durante el crucero." },

    { id: "r_montmartre", name: "Free tour Montmartre (español)", city: "par",
      date: "2026-09-14", time: "15:45", people: 2, status: "confirmado",
      provider: "Civitatis (verificar en el correo de confirmación)", code: "A41342138",
      meeting: "Place Blanche (frente al Moulin Rouge)",
      note: "≈2 h 30. Termina hacia las 18:15 en Sacré-Cœur.",
      pend: ["Referencia visual exacta del guía: VERIFICAR EN COMPROBANTE"] },

    { id: "r_disney",   name: "Disneyland Paris · 1 día, 2 parques", city: "par",
      date: "2026-09-15", time: "", people: 2, status: "pagado",
      addr: "Marne-la-Vallée–Chessy",
      note: "Crush's Coaster cerrado desde el 7 sep 2026 hasta verano 2027.",
      pend: ["Hora de apertura del parque el 15 de septiembre: VERIFICAR unos días antes"] },

    { id: "r_louvre",   name: "Museo del Louvre", city: "par",
      date: "2026-09-16", time: "11:30", people: 2, status: "pagado",
      addr: "Pirámide del Louvre, 75001 París",
      note: "Visita objetivo 2 h 30 – 2 h 45. Solo grandes obras." },

    { id: "r_versalles", name: "Versailles Passport", city: "par",
      date: "2026-09-17", time: "10:00", people: 2, status: "pagado",
      addr: "Place d'Armes, 78000 Versailles",
      note: "Entrada al Palacio a las 10:00.",
      pend: ["Horario de la Flotilla u otras actividades internas: DATO PENDIENTE"] },

    { id: "r_fotos",    name: "Sesión de fotos privada en la Torre Eiffel", city: "par",
      date: "2026-09-14", time: "08:00", people: 2, status: "pendiente",
      provider: "Event Line (a través de GetYourGuide)",
      meeting: "Pont de Bir-Hakeim, 75015 París — en medio del puente, junto a la estatua verde",
      addr: "Pont de Bir-Hakeim, 75015 París",
      note: "Tarifa PRECIO ÚNICO, grupos de hasta 15 personas. Cancelación gratuita hasta las 08:00 del 13 de septiembre.",
      pend: ["CONFIRMAR SI LA COMPRA SE COMPLETÓ: la captura es la pantalla de pago de GetYourGuide, no el comprobante final. Si ya está pagada, cambia status a pagado.",
             "Duración de la sesión: DATO PENDIENTE. El bloque de una hora es provisional.",
             "Localizador: VERIFICAR EN COMPROBANTE"] }
  ],

  /* -------------------------------------------------------------------- DÍAS */
  days: [

    /* ============================ MADRID ============================ */
    {
      id: "d06", city: "mad", date: "2026-09-06", weekday: "Domingo", type: "arrival",
      concept: "Llegada y Madrid de los Austrias",
      depart: "16:30", ret: "23:00",
      note: "Día sin entradas con horario rígido, a propósito: el vuelo puede retrasarse.",
      stops: [
        { id:"m06a", t:"15:00", name:"Llegada · Madrid-Barajas T4", cat:"transport", prio:"P1",
          lat:40.4936, lng:-3.5926, addr:"Terminal 4, Aeropuerto Adolfo Suárez Madrid-Barajas",
          do:"Recoger equipaje documentado y salir a la zona de taxis o al Metro línea 8.",
          pend:["Modo de traslado del aeropuerto al hotel: DATO PENDIENTE (taxi tarifa fija ~30 € o Metro L8 + L1)"] },
        { id:"m06b", t:"16:30", name:"Hotel Quatro Puerta del Sol", cat:"hotel", prio:"P2",
          lat:40.4174, lng:-3.7008, addr:"Calle de Sevilla 4, 28014 Madrid",
          do:"Check-in, dejar maletas y salir ligeros." },
        { id:"m06c", t:"17:15", name:"Puerta del Sol", cat:"sight", prio:"P3", flex:true,
          lat:40.4169, lng:-3.7035, addr:"Puerta del Sol, Madrid",
          what:"La plaza que funciona como centro simbólico de España.",
          why:"Es el punto cero desde el que se miden todas las carreteras del país y la plaza que verás una y otra vez estos días.",
          see:"El Oso y el Madroño, el Kilómetro Cero en el suelo frente al reloj, y el reloj de la Casa de Correos.",
          photo:{ frame:"vertical", where:"Frente a la estatua del Oso y el Madroño, retrocede 5–6 pasos", back:"La estatua con la fachada roja de la Casa de Correos detrás", light:"Tarde" } },
        { id:"m06d", t:"17:45", name:"Plaza Mayor", cat:"sight", prio:"P2",
          lat:40.4155, lng:-3.7074, addr:"Plaza Mayor, Madrid",
          what:"Plaza porticada del siglo XVII, cerrada por completo, con nueve arcos de acceso.",
          why:"Es la imagen clásica del Madrid de los Austrias y el mejor sitio para entender cómo era la ciudad antes de las grandes avenidas.",
          see:"La Casa de la Panadería con sus frescos, la estatua ecuestre de Felipe III y el Arco de Cuchilleros.",
          photo:{ frame:"horizontal", where:"Bajo los soportales del lado sur, mirando al norte", back:"La Casa de la Panadería completa", light:"Tarde" } },
        { id:"m06e", t:"18:15", name:"Bocadillo de calamares", cat:"food", prio:"P3", flex:true,
          lat:40.4156, lng:-3.7080, addr:"Alrededores de Plaza Mayor",
          what:"El bocadillo más madrileño que existe: calamares rebozados dentro de un panecillo, sin más.",
          order:"Un bocadillo de calamares y una caña. Se come de pie.",
          pend:["Bar concreto: DATO PENDIENTE (la zona de Plaza Mayor / Calle Botoneras concentra los clásicos)"] },
        { id:"m06f", t:"18:45", name:"Mercado de San Miguel", cat:"food", prio:"P3", flex:true,
          lat:40.4153, lng:-3.7089, addr:"Plaza de San Miguel s/n, Madrid",
          what:"Mercado de hierro y cristal de 1916 convertido en mercado de tapas.",
          why:"Es turístico y caro, pero visualmente es precioso y sirve para picar algo mirando.",
          order:"Una o dos tapas sueltas, no una comida completa." },
        { id:"m06g", t:"19:15", name:"Madrid de los Austrias", cat:"sight", prio:"P2",
          lat:40.4148, lng:-3.7110, addr:"Plaza de la Villa y alrededores",
          what:"El casco antiguo levantado bajo la dinastía de los Austrias, entre los siglos XVI y XVII.",
          do:"Paseo sin prisa por Plaza de la Villa, Calle del Codo y Plaza del Conde de Miranda." },
        { id:"m06h", t:"19:45", name:"Catedral de la Almudena · exterior", cat:"sight", prio:"P3",
          lat:40.4158, lng:-3.7144, addr:"Calle de Bailén 10, Madrid",
          what:"La catedral de Madrid, terminada en 1993 — mucho más nueva de lo que aparenta.",
          see:"La fachada neoclásica que dialoga con el Palacio Real justo enfrente." },
        { id:"m06i", t:"20:00", name:"Palacio Real · exterior y Plaza de Oriente", cat:"sight", prio:"P3",
          lat:40.4180, lng:-3.7143, addr:"Calle de Bailén s/n, Madrid",
          do:"Solo exterior hoy. La visita guiada es mañana a las 11:00.",
          photo:{ frame:"horizontal", where:"Desde la Plaza de la Armería, esquina sur", back:"Fachada completa del palacio", light:"Atardecer" } },
        { id:"m06j", t:"20:30", name:"Plaza de España", cat:"sight", prio:"P4", flex:true,
          lat:40.4233, lng:-3.7121, addr:"Plaza de España, Madrid",
          see:"El monumento a Cervantes con don Quijote y Sancho." },
        { id:"m06k", t:"20:50", name:"Templo de Debod · atardecer", cat:"sight", prio:"P2",
          lat:40.4240, lng:-3.7178, addr:"Calle de Ferraz 1, Madrid",
          what:"Un templo egipcio auténtico del siglo II a. C., regalado por Egipto a España en 1968 y remontado piedra por piedra aquí.",
          why:"Es el mejor atardecer de Madrid y el reflejo del templo en el estanque es la foto que todo el mundo se lleva.",
          photo:{ frame:"horizontal", where:"En el extremo este del estanque, agachándote un poco", back:"El templo reflejado en el agua", light:"Golden hour — llega 20–30 min antes de la puesta de sol" },
          planB:{ name:"Mirador del Templo de Debod (mismo parque, lado oeste)", why:"Si el estanque está vaciado o en obras, el mirador sobre la Casa de Campo funciona igual de bien" } },
        { id:"m06l", t:"21:45", name:"Cena de tapas", cat:"food", prio:"P2",
          lat:40.4169, lng:-3.7035, addr:"Zona centro",
          order:"Jamón ibérico, tortilla y croquetas. Es la línea que decidimos para España.",
          pend:["Restaurante concreto y si hay reserva: DATO PENDIENTE"] },
        { id:"m06m", t:"23:00", name:"Hotel Quatro Puerta del Sol", cat:"hotel", prio:"P4",
          lat:40.4174, lng:-3.7008, addr:"Calle de Sevilla 4, 28014 Madrid" }
      ]
    },

    {
      id: "d07", city: "mad", date: "2026-09-07", weekday: "Lunes", type: "city",
      concept: "Palacio Real, cocido y flamenco",
      wake: "08:00", depart: "09:00", ret: "23:30",
      stops: [
        { id:"m07a", t:"09:00", name:"Hotel Quatro Puerta del Sol", cat:"hotel", prio:"P4",
          lat:40.4174, lng:-3.7008, addr:"Calle de Sevilla 4, 28014 Madrid" },
        { id:"m07b", t:"09:15", name:"Desayuno", cat:"food", prio:"P3", flex:true,
          lat:40.4172, lng:-3.7069, addr:"Zona Sol / Arenal",
          order:"Tostada con tomate y aceite, o churros con chocolate en San Ginés si te apetece empezar fuerte.",
          pend:["Local del desayuno: DATO PENDIENTE (San Ginés está aprobado para churros, sin día asignado)"] },
        { id:"m07c", t:"10:45", name:"Palacio Real · llegada", cat:"sight", prio:"P1", res:"r_palacio",
          lat:40.4180, lng:-3.7143, addr:"Calle de Bailén s/n, 28071 Madrid",
          do:"Llegar 15 minutos antes del acceso. Pasar control de seguridad.",
          pend:["Puerta de acceso para visitas guiadas: VERIFICAR EN COMPROBANTE"] },
        { id:"m07d", t:"11:00", end:"12:30", name:"Palacio Real · visita guiada", cat:"sight", prio:"P1", res:"r_palacio",
          lat:40.4180, lng:-3.7143, addr:"Calle de Bailén s/n, Madrid",
          what:"El palacio real más grande de Europa occidental por superficie: 135.000 m² y más de 3.400 habitaciones.",
          why:"No es residencia habitual de los reyes, así que se visita casi entero. Los interiores son de una densidad decorativa difícil de imaginar desde fuera.",
          see:"La Escalera Principal, el Salón del Trono, el Salón de Gasparini y la Real Armería.",
          fact:"Se construyó sobre el antiguo Alcázar, que ardió por completo la Nochebuena de 1734.",
          do:"Visita guiada. No se permiten fotos en el interior en la mayoría de las salas." },
        { id:"m07e", t:"12:35", name:"Catedral de la Almudena", cat:"sight", prio:"P3", flex:true,
          lat:40.4158, lng:-3.7144, addr:"Calle de Bailén 10, Madrid",
          do:"Entrada rápida al interior. 15–20 minutos bastan." },
        { id:"m07f", t:"13:00", end:"13:20", name:"FlamencoExport · abanicos", cat:"shop", prio:"P3", flex:true,
          lat:40.4185, lng:-3.7096, addr:"Calle de Campomanes 4, 28013 Madrid",
          what:"Tienda de artículos flamencos: abanicos, mantones, peinetas.",
          do:"Ver abanicos. Confirmado por Ale: 13:00–13:20, entre la Almudena y La Bola.",
          pend:["Horario de apertura de la tienda: DATO PENDIENTE",
                "Coordenadas aproximadas: verificar"] },
        { id:"m07g", t:"13:30", end:"15:15", name:"La Bola", cat:"food", prio:"P1", res:"r_labola",
          lat:40.4200, lng:-3.7112, addr:"Calle de la Bola 5, 28013 Madrid",
          what:"Taberna de 1870 especializada en cocido madrileño cocinado en puchero individual de barro, a fuego de carbón.",
          why:"Es la versión más ortodoxa del plato más madrileño que existe, y la sustituimos deliberadamente por Malacatín.",
          order:"El cocido madrileño completo. Se sirve en tres vuelcos: primero la sopa de fideos, luego los garbanzos con verdura, y al final las carnes.",
          do:"Reserva a las 13:30. Es una comida larga: cuenta 1 h 45 como mínimo." },
        { id:"m07h", t:"15:30", name:"Gran Vía", cat:"sight", prio:"P2",
          lat:40.4200, lng:-3.7058, addr:"Gran Vía, Madrid",
          what:"La gran avenida abierta a principios del siglo XX, con arquitectura de inspiración neoyorquina.",
          see:"El Edificio Metrópolis con su cúpula y la Victoria alada, el Edificio Carrión (Schweppes) y el Edificio Telefónica.",
          photo:{ frame:"vertical", where:"En la esquina de Gran Vía con Calle de Alcalá, sobre la isleta", back:"El Edificio Metrópolis en escorzo", light:"Tarde" } },
        { id:"m07i", t:"16:15", name:"Primark Gran Vía", cat:"shop", prio:"P3", flex:true,
          lat:40.4207, lng:-3.7048, addr:"Gran Vía 32, 28013 Madrid",
          do:"Cinco plantas. Si vas con objetivo concreto, entra por la planta que te interesa y sal." },
        { id:"m07j", t:"17:30", name:"El Corte Inglés Callao", cat:"shop", prio:"P4", flex:true,
          lat:40.4198, lng:-3.7057, addr:"Plaza de Callao 2, 28013 Madrid",
          do:"La terraza de la última planta tiene una de las mejores vistas de Gran Vía y es de acceso libre." },
        { id:"m07k", t:"19:30", name:"Cena ligera", cat:"food", prio:"P3", flex:true,
          lat:40.4160, lng:-3.7010, addr:"Zona Sol / Huertas",
          order:"Ligera: hoy la comida fue un cocido completo.",
          pend:["Local: DATO PENDIENTE"] },
        { id:"m07l", t:"21:00", name:"Cardamomo · tablao flamenco", cat:"show", prio:"P1", res:"r_cardamomo",
          lat:40.4148, lng:-3.6994, addr:"Calle de Echegaray 15, 28014 Madrid",
          what:"Uno de los tablaos con mejor reputación de Madrid, con artistas que han pasado por compañías de primera línea.",
          why:"Elegimos Cardamomo sobre Corral de la Morería. Decisión cerrada.",
          do:"Llegar 20–30 minutos antes: la colocación en la sala suele ser por orden de llegada.",
          pend:["Hora exacta del espectáculo: VERIFICAR EN COMPROBANTE. La hora mostrada (21:00) es provisional."] },
        { id:"m07m", t:"23:00", name:"Hotel Quatro Puerta del Sol", cat:"hotel", prio:"P4",
          lat:40.4174, lng:-3.7008, addr:"Calle de Sevilla 4, 28014 Madrid" }
      ]
    },

    {
      id: "d08", city: "mad", date: "2026-09-08", weekday: "Martes", type: "city",
      concept: "El Madrid ilustrado: Cibeles, Retiro y Prado",
      wake: "08:00", depart: "09:15", ret: "23:00",
      stops: [
        { id:"m08a", t:"09:15", name:"Hotel Quatro Puerta del Sol", cat:"hotel", prio:"P4",
          lat:40.4174, lng:-3.7008, addr:"Calle de Sevilla 4, 28014 Madrid" },
        { id:"m08b", t:"09:45", name:"Plaza de Cibeles", cat:"sight", prio:"P2",
          lat:40.4193, lng:-3.6929, addr:"Plaza de Cibeles, Madrid",
          what:"La fuente de la diosa Cibeles en su carro tirado por leones, de 1782, rodeada de cuatro edificios monumentales.",
          see:"El Palacio de Cibeles (antiguo Palacio de Comunicaciones, hoy ayuntamiento) y el Banco de España.",
          photo:{ frame:"horizontal", where:"Desde la acera del Banco de España, mirando al Palacio de Cibeles", back:"La fuente en primer plano y el palacio blanco detrás", light:"Mañana" } },
        { id:"m08c", t:"10:15", name:"Puerta de Alcalá", cat:"sight", prio:"P3",
          lat:40.4200, lng:-3.6887, addr:"Plaza de la Independencia, Madrid",
          what:"Arco triunfal neoclásico de 1778, anterior al Arco del Triunfo de París.",
          fact:"Sus dos caras son distintas: fíjate en que la decoración no coincide de un lado al otro." },
        { id:"m08d", t:"10:35", end:"11:25", name:"Parque del Retiro", cat:"sight", prio:"P2",
          lat:40.4171, lng:-3.6835, addr:"Parque del Buen Retiro, Madrid",
          what:"125 hectáreas que fueron jardín privado de la corona hasta el siglo XIX.",
          do:"Entrar por la Puerta de la Independencia, bajar al Estanque Grande y salir hacia el Prado por la Puerta de Felipe IV.",
          see:"El Estanque con el monumento a Alfonso XII y el Paseo de la Argentina con sus estatuas.",
          note:"El Palacio de Cristal está descartado: obras hasta 2027." },
        { id:"m08e", t:"11:45", name:"Museo del Prado · llegada", cat:"sight", prio:"P1", res:"r_prado",
          lat:40.4138, lng:-3.6921, addr:"Calle de Ruiz de Alarcón 23, Madrid",
          do:"Llegar 15 minutos antes. Acceso recomendado por la Puerta de los Jerónimos." },
        { id:"m08f", t:"12:00", end:"14:30", name:"Museo del Prado", cat:"sight", prio:"P1", res:"r_prado",
          lat:40.4138, lng:-3.6921, addr:"Calle de Ruiz de Alarcón 23, Madrid",
          what:"La pinacoteca más importante de España y una de las tres o cuatro más importantes del mundo.",
          why:"Concentra la colección real española: es donde están Velázquez y Goya de verdad, no reproducciones.",
          see:"Las Meninas de Velázquez, las Pinturas Negras de Goya, El jardín de las delicias del Bosco, El caballero de la mano en el pecho del Greco y La Trinidad de Rubens.",
          do:"Dos horas y media, solo grandes obras. No intentes verlo entero.",
          pend:["Recorrido interno optimizado sala por sala: DATO PENDIENTE"] },
        { id:"m08g", t:"14:45", name:"Casa Alberto", cat:"food", prio:"P2",
          lat:40.4139, lng:-3.6979, addr:"Calle de las Huertas 18, 28014 Madrid",
          what:"Taberna de 1827, una de las más antiguas de Madrid, en la casa donde Cervantes escribió parte del Quijote.",
          order:"Los callos a la madrileña y el vermut de grifo son sus dos señas. También el rabo de toro.",
          pend:["¿Hay reserva? DATO PENDIENTE"] },
        { id:"m08h", t:"16:15", name:"Barrio de las Letras", cat:"sight", prio:"P3", flex:true,
          lat:40.4140, lng:-3.6975, addr:"Calle de las Huertas y alrededores",
          what:"El barrio donde vivieron Cervantes, Lope de Vega y Quevedo.",
          see:"Los versos del Siglo de Oro escritos en letras doradas sobre el pavimento de Calle Huertas." },
        { id:"m08i", t:"17:30", name:"Mercadona", cat:"shop", prio:"P3", flex:true,
          lat:40.4066, lng:-3.6980, addr:"Ronda de Atocha 26, 28012 Madrid",
          do:"Compra de supermercado. Aceite, conservas, turrón, azafrán.",
          pend:["Coordenadas aproximadas: verificar"] },
        { id:"m08j", t:"18:45", name:"Tiempo flexible", cat:"free", prio:"P4", flex:true,
          lat:40.4174, lng:-3.7008, addr:"Zona centro",
          do:"Colchón deliberado. Si el día se retrasó, aquí es donde se absorbe." },
        { id:"m08k", t:"21:00", name:"Última cena en Madrid", cat:"food", prio:"P2",
          lat:40.4160, lng:-3.7020, addr:"Zona centro",
          pend:["Restaurante y reserva: DATO PENDIENTE"] },
        { id:"m08l", t:"23:00", name:"Hotel · preparar maletas", cat:"hotel", prio:"P1",
          lat:40.4174, lng:-3.7008, addr:"Calle de Sevilla 4, 28014 Madrid",
          do:"Maletas cerradas esta noche. Mañana se sale del hotel a las 07:45." }
      ]
    },

    {
      id: "d09", city: "mad", date: "2026-09-09", weekday: "Miércoles", type: "transfer",
      concept: "Madrid → Estocolmo",
      flight: "f1", wake: "06:45", depart: "07:45",
      stops: [
        { id:"m09a", t:"07:45", name:"Salida del hotel", cat:"hotel", prio:"P1",
          lat:40.4174, lng:-3.7008, addr:"Calle de Sevilla 4, 28014 Madrid",
          do:"Check-out la noche anterior si es posible. Taxi pedido con antelación." },
        { id:"m09b", t:"08:20", name:"Barajas Terminal 4", cat:"transport", prio:"P1",
          lat:40.4936, lng:-3.5926, addr:"Terminal 4, Aeropuerto Adolfo Suárez Madrid-Barajas",
          do:"Facturar equipaje, control de seguridad. Confirmado que IB823 opera desde T4.",
          pend:["Puerta de embarque: VERIFICAR EL DÍA DEL VUELO"] },
        { id:"m09c", t:"10:15", name:"Vuelo IB823 · Madrid → Estocolmo", cat:"flight", prio:"P1",
          addr:"IB823", do:"Salida 10:15 · llegada 14:10." },
        { id:"m09d", t:"14:10", name:"Llegada · Estocolmo-Arlanda", cat:"transport", prio:"P1",
          lat:59.6519, lng:17.9186, addr:"Aeropuerto de Arlanda (ARN)",
          do:"Aterrizaje. El traslado real empieza después de bajar del avión y recoger el equipaje, no aquí." },
        { id:"m09d2", t:"14:40", name:"Recogida de equipaje y salida de la terminal", cat:"transport", prio:"P2",
          lat:59.6519, lng:17.9186, addr:"Aeropuerto de Arlanda (ARN)",
          do:"30 minutos desde el aterrizaje: bajar del avión, caminar a la banda de equipaje y salir de la terminal. Desde aquí sí arranca el traslado al hotel: Arlanda Express o bus Flygbussarna.",
          pend:["Modo de traslado ARN → Hotel C elegido: DATO PENDIENTE. Arlanda Express llega a la Estación Central, a 2 minutos a pie del hotel."] },
        { id:"m09e", t:"15:30", name:"Hotel C Stockholm", cat:"hotel", prio:"P1",
          lat:59.3315, lng:18.0585, addr:"Vasaplan 4, 111 20 Estocolmo",
          do:"Check-in. El hotel está pegado a la Estación Central." },
        { id:"m09f", t:"16:30", name:"Drottninggatan", cat:"sight", prio:"P3", flex:true,
          lat:59.3320, lng:18.0630, addr:"Drottninggatan, Estocolmo",
          what:"La calle peatonal comercial que atraviesa el centro de norte a sur.",
          do:"Primer contacto con la ciudad. Estirar las piernas después del vuelo." },
        { id:"m09g", t:"17:30", name:"Fika", cat:"food", prio:"P2",
          lat:59.3345, lng:18.0575, addr:"Zona Norrmalm",
          what:"La fika no es «tomar café»: es una pausa social codificada, con algo dulce, sin prisa.",
          order:"Kanelbulle (bollo de canela) o kardemummabulle (de cardamomo) con café de filtro.",
          pend:["Cafetería concreta para esta fika: DATO PENDIENTE. Vete-Katten (Kungsgatan 55) está aprobado como konditori histórico y queda cerca del hotel — prioridad prinsesstårta."] },
        { id:"m09h", t:"19:00", name:"Cena", cat:"food", prio:"P3",
          lat:59.3315, lng:18.0585, addr:"Zona centro",
          do:"En Suecia se cena temprano: muchas cocinas cierran hacia las 21:00.",
          pend:["Restaurante: DATO PENDIENTE"] },
        { id:"m09i", t:"21:00", name:"ICEBAR Stockholm", cat:"show", prio:"P2", res:"r_icebar",
          lat:59.3315, lng:18.0585, addr:"Vasaplan 4 (dentro del Hotel C)",
          what:"Un bar mantenido a −5 °C construido enteramente con hielo del río Torne, en Laponia. Se renueva cada año.",
          why:"Está dentro de nuestro propio hotel: cero traslado.",
          do:"Dan poncho térmico y guantes. La visita dura unos 45 minutos y la primera bebida suele ir incluida.",
          pend:["No consta reservado. Confirmar disponibilidad."] }
      ]
    },

    /* ============================ ESTOCOLMO ============================ */
    {
      id: "d10", city: "sto", date: "2026-09-10", weekday: "Jueves", type: "excursion",
      concept: "Mariestad · fábrica FX Airguns",
      wake: "06:00", depart: "06:45", ret: "20:00",
      note: "Hoy son 4 personas. El amigo conduce; no rentamos auto.",
      stops: [
        { id:"s10a", t:"06:45", name:"Salida de Estocolmo en auto", cat:"transport", prio:"P1",
          lat:59.3315, lng:18.0585, addr:"Hotel C Stockholm, Vasaplan 4",
          do:"El amigo pasa por el hotel. Son unos 300 km hasta Mariestad.",
          pend:["Hora exacta de salida acordada con el amigo: DATO PENDIENTE"] },
        { id:"s10b", t:"11:00", name:"Fábrica FX Airguns · Mariestad", cat:"tour", prio:"P1", res:"r_fx",
          lat:58.7100, lng:13.8200, addr:"Mariestad, Suecia",
          what:"La fábrica de FX Airguns, la marca que distribuye Mario.",
          why:"Este es el motivo del viaje. Todo lo demás se organizó alrededor de esta cita.",
          do:"FX confirmó que hay que estar en la fábrica a las 11:00.",
          pend:["Dirección exacta, persona de contacto y duración de la visita: DATO PENDIENTE"] },
        { id:"s10c", t:"14:00", name:"Comida en Mariestad", cat:"food", prio:"P3",
          lat:58.7100, lng:13.8200, addr:"Mariestad",
          pend:["Restaurante: DATO PENDIENTE"] },
        { id:"s10d", t:"15:30", name:"Mariestad · centro y lago Vänern", cat:"sight", prio:"P4", flex:true,
          lat:58.7100, lng:13.8200, addr:"Mariestad",
          what:"Pueblo a orillas del Vänern, el lago más grande de la Unión Europea.",
          pend:["Si la visita a la fábrica se alarga, esta parada es la primera en caer."] },
        { id:"s10e", t:"20:00", name:"Regreso al Hotel C Stockholm", cat:"hotel", prio:"P1",
          lat:59.3315, lng:18.0585, addr:"Vasaplan 4, Estocolmo",
          pend:["Hora estimada de regreso: DATO PENDIENTE (depende de la hora de salida de Mariestad)"] }
      ]
    },

    {
      id: "d11", city: "sto", date: "2026-09-11", weekday: "Viernes", type: "city",
      concept: "Estocolmo a pie: Gamla Stan, café y miradores",
      wake: "07:30", depart: "08:45", ret: "20:30",
      note: "Hoy nos movemos a pie y en transporte público. El free tour de las 13:00 parte el día en dos: mañana de museo y tarde de barrios.",
      stops: [
        { id:"s11a", t:"08:45", name:"Hotel C Stockholm", cat:"hotel", prio:"P4",
          lat:59.3315, lng:18.0585, addr:"Vasaplan 4, Estocolmo" },
        { id:"s11b", t:"09:00", name:"Desayuno", cat:"food", prio:"P3", flex:true,
          lat:59.3315, lng:18.0585, addr:"Zona Norrmalm",
          pend:["Local: DATO PENDIENTE"] },
        { id:"s11c", t:"10:00", end:"11:15", name:"Stadshuset · Ayuntamiento", cat:"sight", prio:"P2",
          lat:59.3275, lng:18.0543, addr:"Hantverkargatan 1, Estocolmo",
          what:"El Ayuntamiento de Estocolmo, de 1923, con ocho millones de ladrillos y una torre de 106 metros.",
          why:"Aquí se celebra el banquete de los Premios Nobel cada 10 de diciembre, en la Sala Azul.",
          see:"La Sala Azul (que no es azul) y la Sala Dorada, con 18 millones de teselas de mosaico.",
          do:"El interior solo se visita con guía y en horarios fijos.",
          pend:["Horario de la visita guiada en español o inglés: DATO PENDIENTE"],
          photo:{ frame:"horizontal", where:"Desde el patio interior mirando hacia la torre", back:"La torre con las tres coronas doradas", light:"Mañana" } },
        { id:"s11b2", t:"11:45", end:"12:30", name:"Comida temprana", cat:"food", prio:"P2",
          lat:59.3290, lng:18.0650, addr:"Entre Stadshuset y Gustav Adolfs torg",
          do:"Comer antes del tour: son 2 h 30 de pie y termina a las 15:30.",
          pend:["Restaurante: DATO PENDIENTE. Debe quedar en la línea Stadshuset → Gustav Adolfs torg, sin desvío."] },
        { id:"s11d0", t:"12:45", name:"Gustav Adolfs torg · punto de encuentro", cat:"transport", prio:"P1", res:"r_freesto",
          lat:59.3300, lng:18.0690, addr:"Gustav Adolfs torg, Estocolmo",
          do:"Llegar 15 minutos antes. Localizador A41038311. Hoy son 4 personas: se suma el amigo.",
          pend:["Punto exacto dentro de la plaza y referencia visual del guía: VERIFICAR EN COMPROBANTE"] },
        { id:"s11d", t:"13:00", end:"15:30", name:"Free tour por Estocolmo", cat:"tour", prio:"P1", res:"r_freesto",
          lat:59.3300, lng:18.0690, addr:"De Gustav Adolfs torg a Stortorget",
          what:"Recorrido a pie en español de 2 h 30, gratuito con propina.",
          do:"Termina en Stortorget, en el corazón de Gamla Stan: la siguiente parada ya estás ahí.",
          note:"Reserva A41038311 · 4 personas · confirmada." },
        { id:"s11e", t:"15:40", name:"Gamla Stan · fotos y compras", cat:"sight", prio:"P2",
          lat:59.3254, lng:18.0710, addr:"Stortorget, Gamla Stan, Estocolmo",
          what:"El casco medieval sobre su propia isla, con calles del siglo XIII.",
          see:"Las casas de colores de Stortorget y el callejón Mårten Trotzigs gränd, de 90 cm de ancho.",
          do:"El tour termina justo aquí. Compras suecas auténticas y pequeñas: cerámica, textil, dalahäst de madera.",
          photo:{ frame:"vertical", where:"En el lado norte de Stortorget, con el pozo a tu izquierda", back:"La fachada ocre y la roja juntas", light:"Tarde" } },
        { id:"s11f", t:"16:30", name:"Skeppsholmen", cat:"sight", prio:"P4", flex:true,
          lat:59.3253, lng:18.0840, addr:"Skeppsholmen, Estocolmo",
          what:"Isla tranquila unida por el puente de Skeppsholmsbron, con una de las mejores vistas del casco antiguo.",
          do:"Es la primera parada que cae si el día se alarga: queda al este y el resto de la tarde va hacia el sur.",
          pend:["POSICIÓN EN EL DÍA POR CONFIRMAR: no consta en qué momento quedó dentro de la jornada. Colocada aquí como opcional."],
          photo:{ frame:"horizontal", where:"En mitad del puente Skeppsholmsbron", back:"La silueta completa de Gamla Stan sobre el agua", light:"Tarde" } },
        { id:"s11g", t:"17:15", name:"Drop Coffee", cat:"food", prio:"P2",
          lat:59.3164, lng:18.0620, addr:"Wollmar Yxkullsgatan 10, Södermalm, Estocolmo",
          what:"Tostador de café de especialidad, de los más reconocidos de Escandinavia.",
          why:"Aquí la fika es por el café, no por el decorado. Cumple la regla de café realmente bueno.",
          order:"Un filtro V60 de origen único y un kardemummabulle.",
          pend:["Horario de cierre: VERIFICAR. Muchos cafés de especialidad en Estocolmo cierran a las 17:00 o 18:00. Si cierra antes, hay que adelantarlo o cambiarlo."] },
        { id:"s11h", t:"18:15", name:"Monteliusvägen", cat:"sight", prio:"P2",
          lat:59.3211, lng:18.0568, addr:"Monteliusvägen, Södermalm, Estocolmo",
          what:"Un paseo peatonal de 500 metros en alto sobre el lago Mälaren.",
          why:"Es la mejor vista panorámica de Estocolmo y es gratis.",
          do:"A mediados de septiembre el sol se pone hacia las 19:30: esta hora cae dentro de la luz buena.",
          photo:{ frame:"horizontal", where:"En el tramo central del paseo, junto a los bancos de madera", back:"El Ayuntamiento a la izquierda y Gamla Stan a la derecha, con el agua delante", light:"Golden hour" } },
        { id:"s11i", t:"19:00", name:"Paseo por Södermalm", cat:"sight", prio:"P4", flex:true,
          lat:59.3180, lng:18.0640, addr:"Södermalm, Estocolmo",
          do:"Paseo natural, sin objetivo. Es el barrio con más carácter de la ciudad." },
        { id:"s11j", t:"19:30", name:"Tunnbrödsrulle en un gatukök", cat:"food", prio:"P3",
          lat:59.3180, lng:18.0640, addr:"Södermalm",
          what:"Comida callejera sueca: salchicha, puré de papa, cebolla frita y salsa, todo enrollado en pan plano.",
          pend:["GATUKÖK CONCRETO POR ELEGIR. Criterios acordados: autenticidad, horario real de apertura y ruta natural desde Monteliusvägen — máximo 1–1,5 km adicionales."] },
        { id:"s11k", t:"20:30", name:"Hotel C Stockholm", cat:"hotel", prio:"P4",
          lat:59.3315, lng:18.0585, addr:"Vasaplan 4, Estocolmo",
          do:"Preparar maletas: mañana hay crucero y vuelo.",
          pend:["El regreso pasó de 19:45–20:00 a 20:30 porque el tour es a las 13:00, no a mediodía. Si quieres volver antes, lo que cae es Skeppsholmen."] }
      ]
    },
    {
      id: "d12", city: "sto", date: "2026-09-12", weekday: "Sábado", type: "hybrid",
      concept: "Crucero por el archipiélago y vuelo a París",
      flight: "f2", cutoff: "13:30", wake: "07:30", depart: "09:00",
      note: "Día híbrido: turismo por la mañana, vuelo por la tarde. Después del corte de las 13:30 no hay margen para nada más.",
      stops: [
        { id:"s12a", t:"09:00", name:"Check-out · Hotel C Stockholm", cat:"hotel", prio:"P1",
          lat:59.3315, lng:18.0585, addr:"Vasaplan 4, Estocolmo",
          do:"Check-out con maletas. Dejarlas en consigna del hotel: volvemos a pasar por aquí camino del aeropuerto.",
          pend:["Confirmar que el hotel guarda equipaje después del check-out"] },
        { id:"s12b", t:"09:30", name:"Vete-Katten", cat:"food", prio:"P3", flex:true,
          lat:59.3345, lng:18.0575, addr:"Kungsgatan 55, Estocolmo",
          what:"Konditori histórico de 1928, con salones interiores que parecen la casa de una abuela sueca.",
          order:"Prinsesstårta (prioridad). Si quieren compartir algo más: dammsugare o chokladboll.",
          do:"Se puede pedir para llevar si el tiempo aprieta." },
        { id:"s12c", t:"10:15", name:"Muelle 15 · Strandvägen", cat:"transport", prio:"P1", res:"r_crucerosto",
          lat:59.3320, lng:18.0790, addr:"Strandvägen, muelle 15, Estocolmo",
          do:"Llegar 15 minutos antes del embarque. Buscar el barco M/S Östanå I.",
          pend:["Coordenadas exactas del muelle 15: verificar. Strandvägen tiene varios embarcaderos numerados seguidos."] },
        { id:"s12d", t:"10:30", end:"13:00", name:"Crucero por el archipiélago", cat:"tour", prio:"P1", res:"r_crucerosto",
          lat:59.3320, lng:18.0790, addr:"Salida desde Strandvägen, muelle 15",
          what:"Navegación de 2 h 30 por el archipiélago de Estocolmo, que tiene unas 30.000 islas.",
          why:"Es la manera de ver la ciudad desde el agua, que es como se entiende.",
          do:"Barco M/S Östanå I. Siéntense en cubierta si el clima lo permite; llevar capa extra, en el agua hace más frío.",
          photo:{ frame:"horizontal", where:"En la cubierta de popa, al salir del puerto", back:"La silueta de la ciudad alejándose", light:"Mañana" } },
        { id:"s12e", t:"13:30", name:"CORTE OPERATIVO · recoger equipaje", cat:"transport", prio:"P1",
          lat:59.3315, lng:18.0585, addr:"Hotel C Stockholm, Vasaplan 4",
          do:"A partir de aquí el día es exclusivamente traslado. No añadir nada." },
        { id:"s12f", t:"14:20", name:"Traslado al aeropuerto de Arlanda", cat:"transport", prio:"P1",
          lat:59.6519, lng:17.9186, addr:"Aeropuerto de Arlanda (ARN)",
          do:"Arlanda Express desde la Estación Central: 20 minutos, sale cada 10–15 minutos. El hotel está a 2 minutos a pie de la estación.",
          pend:["Devolución del auto al amigo / garaje AIMO Park (Birger Jarlsgatan 6): confirmar si esta gestión ocurre hoy y a qué hora."] },
        { id:"s12g", t:"15:20", name:"Arlanda · facturación y seguridad", cat:"transport", prio:"P1",
          lat:59.6519, lng:17.9186, addr:"Arlanda (ARN)",
          pend:["Terminal de salida de SK579 y puerta de embarque: VERIFICAR EL DÍA DEL VUELO"] },
        { id:"s12h", t:"17:50", name:"Vuelo SK579 · Estocolmo → París", cat:"flight", prio:"P1",
          addr:"SK579", do:"Salida 17:50 · llegada CDG 20:25." },
        { id:"s12i", t:"20:25", name:"Llegada · París-Charles de Gaulle", cat:"transport", prio:"P1",
          lat:49.0097, lng:2.5479, addr:"Aeropuerto Charles de Gaulle (CDG)",
          do:"Recoger equipaje y traslado al hotel.",
          pend:["Modo de traslado CDG → hotel: DATO PENDIENTE. A esa hora el taxi tarifa fija a la orilla derecha (~56 €) es lo más razonable con maletas."] },
        { id:"s12j", t:"21:45", name:"Hotel en París · check-in", cat:"hotel", prio:"P1",
          lat:48.8664, lng:2.3268, addr:"Meliá Paris Vendôme, 8 Rue Cambon, 75001 París",
          do:"Check-in a partir de las 15:00. Llegando a esta hora, la habitación ya está lista." }
      ]
    },

    /* ============================== PARÍS ============================== */
    {
      id: "d13", city: "par", date: "2026-09-13", weekday: "Domingo", type: "city",
      concept: "París monumental y el Sena",
      wake: "08:00", depart: "09:30", ret: "22:30",
      stops: [
        { id:"p13a", t:"09:30", name:"Hotel", cat:"hotel", prio:"P4",
          lat:48.8664, lng:2.3268, addr:"Meliá Paris Vendôme, 8 Rue Cambon, 75001 París", pend:["Confirmar hotel: todos los traslados de hoy parten de aquí"] },
        { id:"p13b", t:"10:00", name:"Desayuno", cat:"food", prio:"P3", flex:true,
          addr:"Cerca del hotel", pend:["Boulangerie o café: DATO PENDIENTE"] },
        { id:"p13e", t:"10:30", end:"11:05", name:"Jardín de las Tullerías", cat:"sight", prio:"P3",
          lat:48.8635, lng:2.3270, addr:"Jardin des Tuileries, 75001 París",
          what:"El jardín de estilo francés diseñado por Le Nôtre, el mismo de Versalles.",
          do:"Empezamos aquí porque el hotel está a cinco minutos, en Rue Cambon. Paseo por el eje central; las sillas verdes son públicas.",
          note:"Si el pebetero/globo olímpico sigue instalado, está aquí.",
          pend:["Confirmar si el globo olímpico sigue en pie en septiembre de 2026"] },
        { id:"p13d", t:"11:15", name:"Place de la Concorde", cat:"sight", prio:"P3",
          lat:48.8656, lng:2.3212, addr:"Place de la Concorde, 75008 París",
          what:"La plaza más grande de París, donde estuvo la guillotina durante la Revolución.",
          see:"El obelisco de Luxor, de 3.300 años, regalado por Egipto en 1836." },
        { id:"p13c", t:"11:45", name:"Pont Alexandre III", cat:"sight", prio:"P2",
          lat:48.8639, lng:2.3134, addr:"Pont Alexandre III, 75008 París",
          what:"El puente más ornamentado de París, construido para la Exposición Universal de 1900.",
          do:"Desde aquí se sube por la Avenue Winston Churchill directo a los Campos Elíseos: la ruta encadena sola.",
          why:"Es puro art nouveau: farolas, querubines, ninfas y cuatro columnas doradas de 17 metros.",
          photo:{ frame:"vertical", where:"En la esquina noreste del puente, junto a la columna dorada", back:"La perspectiva del puente con los Inválidos al fondo", light:"Mañana" } },
        { id:"p13f", t:"13:15", name:"Comida", cat:"food", prio:"P2",
          addr:"Zona Tullerías / Concorde", pend:["Restaurante: DATO PENDIENTE"] },
        { id:"p13g", t:"14:45", name:"Ladurée · macarons", cat:"food", prio:"P4", flex:true,
          lat:48.8709, lng:2.3038, addr:"75 Avenue des Champs-Élysées, 75008 París",
          what:"La casa que inventó el macaron de dos tapas con relleno, en 1930.",
          order:"Una caja pequeña surtida. Los clásicos: pistacho, rosa-frambuesa, caramelo salado.",
          do:"Sin desvío especial: queda en la ruta de los Campos Elíseos." },
        { id:"p13h", t:"15:15", name:"Campos Elíseos", cat:"sight", prio:"P3",
          lat:48.8700, lng:2.3050, addr:"Avenue des Champs-Élysées, París",
          do:"Subir caminando hacia el Arco. Son 1,9 km desde Concorde." },
        { id:"p13i", t:"16:10", name:"Arco del Triunfo · exterior", cat:"sight", prio:"P2",
          lat:48.8738, lng:2.2950, addr:"Place Charles de Gaulle, 75008 París",
          what:"Arco encargado por Napoleón en 1806 para celebrar Austerlitz.",
          do:"SOLO EXTERIOR. Decisión cerrada: no subimos ni compramos entrada.",
          note:"Para cruzar a la isla central usa el paso subterráneo, nunca la rotonda.",
          photo:{ frame:"vertical", where:"En la isla central, lado este, retrocediendo hasta el borde", back:"El arco completo de frente", light:"Tarde" } },
        { id:"p13j", t:"16:30", end:"19:00", name:"Free tour Arco y Campos Elíseos", cat:"tour", prio:"P1", res:"r_freearco",
          lat:48.8738, lng:2.2950, addr:"Zona Arco del Triunfo",
          what:"Recorrido guiado en español de unas 2 h 30 que termina en la zona de Trocadéro.",
          do:"Llegar 15 minutos antes.",
          pend:["PUNTO EXACTO DE ENCUENTRO Y REFERENCIA VISUAL: VERIFICAR EN COMPROBANTE. No lo invento.",
                "Hora exacta de finalización: estimada en 19:00, junto a Trocadéro"] },
        { id:"p13k", t:"19:20", name:"Trocadéro · fotos de la Torre Eiffel", cat:"sight", prio:"P2",
          lat:48.8629, lng:2.2876, addr:"Place du Trocadéro, 75016 París",
          what:"La explanada del Palacio de Chaillot, elevada justo enfrente de la Torre Eiffel.",
          why:"Es la vista frontal completa de la torre. No subimos a la torre — decisión cerrada — pero de verla y fotografiarla se trata.",
          do:"El tour termina prácticamente aquí: solo quedan unos minutos de foto antes de bajar hacia el embarque.",
          photo:{ frame:"vertical", where:"En la explanada entre las dos alas del Palacio de Chaillot, en el borde de la balaustrada", back:"La Torre Eiffel completa y centrada", light:"Golden hour", tip:"Baja unos escalones hacia los jardines para quitarte gente de encima." } },
        { id:"p13l", t:"19:35", name:"Port de la Bourdonnais · embarque", cat:"transport", prio:"P1", res:"r_bateaux",
          lat:48.8600, lng:2.2950, addr:"Port de la Bourdonnais, 75007 París",
          do:"Bajar del Trocadéro cruzando el Pont d'Iéna. Con el crucero fijado al Plan B (20:00), llegar a las 19:35 deja 25 minutos de margen real para hacer fila y embarcar." },
        { id:"p13m", t:"20:00", end:"21:10", name:"Crucero Bateaux Parisiens", cat:"tour", prio:"P1", res:"r_bateaux",
          lat:48.8600, lng:2.2950, addr:"Port de la Bourdonnais, 75007 París",
          what:"Crucero panorámico por el Sena de aproximadamente una hora, con el circuito clásico hasta Notre-Dame y vuelta.",
          do:"PLAN B CONFIRMADO COMO PRINCIPAL: el horario de las 19:00 no da tiempo real desde el free tour. Se embarca en la salida de las 20:00.",
          note:"El atardecer es hacia las 20:07: con el horario de las 20:00 se ve el cambio de luz durante el crucero, no antes de subir." },
        { id:"p13n", t:"21:30", name:"Cena", cat:"food", prio:"P2",
          addr:"Zona Torre Eiffel / Champ de Mars", pend:["Restaurante: DATO PENDIENTE",
                "Hora aproximada: calculada sobre el fin del crucero a las 21:10 más 20 min para desembarcar y llegar caminando. Ajustar cuando se elija el lugar."] },
        { id:"p13o", t:"23:00", name:"Hotel", cat:"hotel", prio:"P4", lat:48.8664, lng:2.3268, addr:"Meliá Paris Vendôme, 8 Rue Cambon, 75001 París" }
      ]
    },

    {
      id: "d14", city: "par", date: "2026-09-14", weekday: "Lunes", type: "city",
      concept: "Fotos al amanecer, Galeries Lafayette y Montmartre",
      wake: "06:15", depart: "07:00", ret: "22:00",
      note: "Hoy NO se vuelve al hotel después del desayuno. La sesión de fotos a las 08:00 fija el arranque del día.",
      stops: [
        { id:"p14a", t:"07:00", name:"Salida del hotel", cat:"hotel", prio:"P1", lat:48.8664, lng:2.3268, addr:"Meliá Paris Vendôme, 8 Rue Cambon, 75001 París",
          do:"Salir arreglados: la sesión empieza a las 08:00 y no hay margen para volver.",
          note:"El punto de encuentro está a unos 25 min: metro o taxi." },
        { id:"p14b", t:"07:45", name:"Pont de Bir-Hakeim · punto de encuentro", cat:"transport", prio:"P1", res:"r_fotos",
          lat:48.8558, lng:2.2866, addr:"Pont de Bir-Hakeim, 75015 París",
          do:"El punto de encuentro está EN MEDIO DEL PUENTE, junto a la estatua verde. Por encima pasa la línea 6 del metro, en el tramo elevado entre Bir-Hakeim y Passy.",
          why:"Llegar 15 minutos antes. El proveedor advierte que hay que ser puntual para conservar el lugar.",
          note:"Proveedor: Event Line, a través de GetYourGuide." },
        { id:"p14c", t:"08:00", end:"09:00", name:"Sesión de fotos en la Torre Eiffel", cat:"tour", prio:"P1", res:"r_fotos",
          lat:48.8558, lng:2.2866, addr:"Pont de Bir-Hakeim, 75015 París",
          what:"Sesión fotográfica de pareja con la Torre Eiffel de fondo, desde el puente de Bir-Hakeim.",
          why:"Es uno de los encuadres más reconocibles de París: el viaducto metálico del metro enmarca la torre en perspectiva.",
          do:"A las 08:00 de un lunes de septiembre la luz es baja y el puente está mucho menos concurrido que a media mañana.",
          photo:{ frame:"vertical", where:"En la pasarela central del puente, bajo el viaducto del metro", back:"La torre al fondo, con las columnas del viaducto repitiéndose a los lados", light:"Primera hora" },
          pend:["Duración real de la sesión: DATO PENDIENTE. El bloque de una hora es provisional."] },
        { id:"p14c2", t:"09:15", name:"Desayuno especial", cat:"food", prio:"P2",
          addr:"Por confirmar",
          do:"Desayuno con intención, no de trámite. No volvemos al hotel después.",
          pend:["Local sin cerrar. Candidato registrado: La Cuisine (Royal Monceau). Con la sesión terminando en Bir-Hakeim, conviene un sitio de camino a Haussmann, no un desvío.",
                "CONSECUENCIA DEL NUEVO HORARIO: Galeries Lafayette se movió de 10:00 a 10:30."] },
        { id:"p14d", t:"10:30", end:"13:00", name:"Galeries Lafayette Haussmann", cat:"shop", prio:"P2",
          lat:48.8736, lng:2.3320, addr:"40 Boulevard Haussmann, 75009 París",
          what:"Gran almacén de 1912 con una cúpula de vidrio policromado de 43 metros de alto.",
          do:"Mini-ruta interna acordada, en este orden: (1) la Coupole y la pasarela de cristal, (2) la terraza gratuita de la última planta, (3) moda, (4) perfumería de nicho — prioridad alta, (5) belleza, (6) parafarmacia, (7) mostrador de Tax Free antes de salir.",
          note:"Perfumería de nicho: 6–8 perfumes máximo para probar. Anota precios para comparar contra México y Estados Unidos.",
          photo:{ frame:"vertical", where:"En la pasarela de cristal del centro, o desde la barandilla de la 3ª planta mirando arriba", back:"La cúpula completa", light:"Interior — sube la exposición" } },
        { id:"p14e", t:"13:15", name:"Comida", cat:"food", prio:"P2",
          addr:"Zona Opéra / Haussmann", pend:["Restaurante: DATO PENDIENTE"] },
        { id:"p14f", t:"14:30", name:"Galerie Vivienne y Palais-Royal", cat:"sight", prio:"P4", flex:true,
          lat:48.8666, lng:2.3400, addr:"4 Rue des Petits Champs, 75002 París",
          what:"Pasaje cubierto de 1823 con mosaicos en el suelo y claraboyas, y el patio del Palais-Royal con las columnas de Buren.",
          do:"SOLO si cabe sin prisas. Es la primera parada que se sacrifica si vamos justos.",
          photo:{ frame:"vertical", where:"Entre las columnas blancas y negras del patio del Palais-Royal", back:"La perspectiva de columnas repitiéndose", light:"Mediodía" } },
        { id:"p14g", t:"15:30", name:"Place Blanche · punto de encuentro", cat:"transport", prio:"P1", res:"r_montmartre",
          lat:48.8840, lng:2.3325, addr:"Place Blanche, 75018 París",
          do:"Llegar 15 minutos antes. La plaza se reconoce de inmediato: el Moulin Rouge con su molino rojo está justo ahí.",
          pend:["Referencia visual del guía (paraguas, cartel, color): VERIFICAR EN COMPROBANTE"] },
        { id:"p14h", t:"15:45", end:"18:15", name:"Free tour Montmartre", cat:"tour", prio:"P1", res:"r_montmartre",
          lat:48.8840, lng:2.3325, addr:"De Place Blanche a Sacré-Cœur",
          what:"Recorrido en español de unas 2 h 30 por el barrio, no solo por la basílica.",
          why:"Montmartre era un pueblo independiente hasta 1860. El tour recorre la lógica del barrio: los viñedos, los estudios de los pintores, las plazas.",
          do:"Termina hacia las 18:15 en Sacré-Cœur." },
        { id:"p14i", t:"18:30", name:"Sacré-Cœur y sus escalinatas", cat:"sight", prio:"P2",
          lat:48.8867, lng:2.3431, addr:"35 Rue du Chevalier de la Barre, 75018 París",
          what:"Basílica de piedra blanca terminada en 1914, en el punto más alto de la ciudad.",
          fact:"La piedra de Château-Landon que usaron segrega calcita al contacto con el agua: por eso se mantiene blanca sola.",
          photo:{ frame:"horizontal", where:"En el mirador de la escalinata, unos 20 escalones por debajo de la explanada", back:"París entero extendido al fondo", light:"Golden hour" } },
        { id:"p14j", t:"19:30", name:"Cena en Montmartre", cat:"food", prio:"P3",
          lat:48.8850, lng:2.3400, addr:"Montmartre", pend:["Restaurante: DATO PENDIENTE"] },
        { id:"p14k", t:"22:00", name:"Hotel", cat:"hotel", prio:"P4", lat:48.8664, lng:2.3268, addr:"Meliá Paris Vendôme, 8 Rue Cambon, 75001 París" }
      ]
    },

    {
      id: "d15", city: "par", date: "2026-09-15", weekday: "Martes", type: "disney",
      concept: "Disneyland Paris · 1 día, 2 parques",
      wake: "06:30", depart: "07:30", ret: "23:30",
      note: "Un solo día. Decisión cerrada: no hay segundo día.",
      stops: [
        { id:"p15a", t:"07:30", name:"Salida del hotel", cat:"hotel", prio:"P1", lat:48.8664, lng:2.3268, addr:"Meliá Paris Vendôme, 8 Rue Cambon, 75001 París",
          do:"Desayuno rápido o comprado la noche anterior. Hoy se madruga." },
        { id:"p15b", t:"07:50", name:"Estación Auber · RER A", cat:"transport", prio:"P1",
          lat:48.8725, lng:2.3290, addr:"Estación Auber, 75009 París",
          do:"Auber está a 8 minutos a pie del hotel y es RER A directo a Disney: sin taxi y sin transbordo.",
          pend:["Andén exacto del RER A dirección Marne-la-Vallée: verificar en el panel. No todos los trenes de la línea A llegan a Chessy — el destino debe decir MARNE-LA-VALLÉE–CHESSY."] },
        { id:"p15c", t:"08:45", name:"Marne-la-Vallée–Chessy", cat:"transport", prio:"P1",
          lat:48.8700, lng:2.7820, addr:"Marne-la-Vallée–Chessy",
          do:"La estación está literalmente en la entrada del complejo. Salir, cruzar la explanada, controles de seguridad, torniquetes." },
        { id:"p15d", t:"09:15", name:"Entrada a los parques", cat:"tour", prio:"P1", res:"r_disney",
          lat:48.8700, lng:2.7820, addr:"Disneyland Paris",
          do:"Boleto de 1 día y 2 parques: se puede pasar de Disneyland Park a Walt Disney Studios y volver.",
          pend:["HORA DE APERTURA del 15 de septiembre: VERIFICAR unos días antes. La hora mostrada es provisional.",
                "ORDEN DE ATRACCIONES POR PRIORIDAD (🔴 A / 🟠 B / ⚪ opcional): DATO PENDIENTE. No lo invento — hay que definirlo con el mapa y los horarios reales del día.",
                "Crush's Coaster está CERRADO desde el 7 de septiembre de 2026 hasta verano de 2027."] },
        { id:"p15e", t:"13:00", name:"Comida en el parque", cat:"food", prio:"P3",
          lat:48.8700, lng:2.7820, addr:"Disneyland Paris", pend:["Restaurante y si requiere reserva: DATO PENDIENTE"] },
        { id:"p15f", t:"16:00", name:"Descanso", cat:"free", prio:"P4", flex:true,
          lat:48.8700, lng:2.7820, addr:"Disneyland Paris",
          do:"Pausa deliberada. Un día completo de parque son más de 20.000 pasos." },
        { id:"p15g", t:"21:00", name:"Espectáculo nocturno", cat:"show", prio:"P2",
          lat:48.8700, lng:2.7820, addr:"Frente al castillo, Disneyland Park",
          do:"Colocarse 30–40 minutos antes en la parte central de Main Street.",
          pend:["Nombre y hora del espectáculo nocturno del 15 de septiembre: VERIFICAR unos días antes"] },
        { id:"p15h", t:"22:15", name:"Regreso · RER A a París", cat:"transport", prio:"P1",
          lat:48.8700, lng:2.7820, addr:"Marne-la-Vallée–Chessy",
          do:"Salir en cuanto termine el espectáculo o esperar 20 minutos a que se vacíe el andén. Dirección: hacia París (Poissy / Cergy / Saint-Germain-en-Laye).",
          pend:["Hora del último RER A hacia París: VERIFICAR el mismo día en la estación. Es el dato que no se puede fallar."] },
        { id:"p15i", t:"23:30", name:"Hotel", cat:"hotel", prio:"P4", lat:48.8664, lng:2.3268, addr:"Meliá Paris Vendôme, 8 Rue Cambon, 75001 París" }
      ]
    },

    {
      id: "d16", city: "par", date: "2026-09-16", weekday: "Miércoles", type: "city",
      concept: "Louvre e Île de la Cité",
      wake: "08:00", depart: "09:30", ret: "22:30",
      stops: [
        { id:"p16a", t:"09:30", name:"Hotel", cat:"hotel", prio:"P4", lat:48.8664, lng:2.3268, addr:"Meliá Paris Vendôme, 8 Rue Cambon, 75001 París" },
        { id:"p16b", t:"09:45", name:"Desayuno", cat:"food", prio:"P3", flex:true,
          addr:"Cerca del hotel", pend:["Local: DATO PENDIENTE"] },
        { id:"p16c", t:"11:15", name:"Louvre · llegada y acceso", cat:"sight", prio:"P1", res:"r_louvre",
          lat:48.8606, lng:2.3376, addr:"Pirámide del Louvre, 75001 París",
          do:"Llegar 15 minutos antes de la hora de la entrada. Con entrada horaria comprada, el acceso por la Pirámide tiene fila propia.",
          pend:["Acceso recomendado (Pirámide / Porte des Lions / Carrousel): VERIFICAR EN COMPROBANTE"] },
        { id:"p16d", t:"11:30", end:"14:15", name:"Museo del Louvre", cat:"sight", prio:"P1", res:"r_louvre",
          lat:48.8606, lng:2.3376, addr:"Rue de Rivoli, 75001 París",
          what:"Antiguo palacio real convertido en museo en 1793. 35.000 obras expuestas sobre 72.000 m².",
          why:"Es imposible verlo entero y no vamos a intentarlo. Vamos a las grandes obras, 2 h 30 – 2 h 45.",
          see:"La Gioconda, la Victoria de Samotracia, la Venus de Milo, La libertad guiando al pueblo y La coronación de Napoleón.",
          do:"Empezar por Denon, que es donde está casi todo lo anterior. Los baños del ala Richelieu suelen tener menos fila.",
          pend:["RECORRIDO INTERNO OPTIMIZADO sala por sala: DATO PENDIENTE"] },
        { id:"p16e", t:"14:30", name:"Comida", cat:"food", prio:"P2",
          lat:48.8637, lng:2.3372, addr:"Zona Palais-Royal / Rivoli", pend:["Restaurante: DATO PENDIENTE"] },
        { id:"p16f", t:"16:00", name:"Île de la Cité", cat:"sight", prio:"P2",
          lat:48.8550, lng:2.3470, addr:"Île de la Cité, 75004 París",
          what:"La isla donde nació París: aquí estaba Lutecia, el asentamiento romano.",
          do:"Recorrido a pie por la isla." },
        { id:"p16g", t:"16:30", name:"Sainte-Chapelle", cat:"sight", prio:"P2",
          lat:48.8554, lng:2.3450, addr:"10 Boulevard du Palais, 75001 París",
          what:"Capilla gótica del siglo XIII con 1.113 escenas en 15 vidrieras de 15 metros de alto.",
          why:"El efecto de la capilla alta con el sol atravesando el vidrio no se parece a nada.",
          do:"Está dentro del recinto del Palacio de Justicia: hay control de seguridad tipo aeropuerto.",
          pend:["ENTRADA NO COMPRADA. Requiere reserva de horario. Decidir y comprar antes de viajar."] },
        { id:"p16h", t:"17:45", name:"Notre-Dame", cat:"sight", prio:"P2",
          lat:48.8530, lng:2.3499, addr:"6 Parvis Notre-Dame, 75004 París",
          what:"La catedral gótica reabierta tras el incendio de 2019.",
          do:"El acceso al interior es gratuito pero requiere reserva de franja horaria.",
          pend:["RESERVA GRATUITA NO HECHA. Se abre con pocos días de antelación. DATO PENDIENTE."] },
        { id:"p16i", t:"19:00", name:"Le Marais y Place des Vosges", cat:"sight", prio:"P3", flex:true,
          lat:48.8555, lng:2.3655, addr:"Place des Vosges, 75004 París",
          what:"La plaza más antigua de París, de 1612, con 36 pabellones idénticos de ladrillo rojo y piedra.",
          do:"Paseo por el Marais hasta la plaza." },
        { id:"p16j", t:"20:30", name:"Cena en el Marais", cat:"food", prio:"P2",
          lat:48.8570, lng:2.3600, addr:"Le Marais, París",
          pend:["Restaurante del Marais: EN PAUSA DELIBERADA, sin cerrar. También sigue pendiente dónde tomar la sopa de cebolla."] },
        { id:"p16k", t:"22:30", name:"Hotel", cat:"hotel", prio:"P4", lat:48.8664, lng:2.3268, addr:"Meliá Paris Vendôme, 8 Rue Cambon, 75001 París" }
      ]
    },

    {
      id: "d17", city: "par", date: "2026-09-17", weekday: "Jueves", type: "versailles",
      concept: "Versalles y cena especial",
      wake: "06:45", depart: "07:45", ret: "23:30",
      stops: [
        { id:"p17a", t:"07:45", name:"Salida del hotel", cat:"hotel", prio:"P1", lat:48.8664, lng:2.3268, addr:"Meliá Paris Vendôme, 8 Rue Cambon, 75001 París",
          do:"Desayuno rápido. La entrada al Palacio es a las 10:00 y no admite retraso." },
        { id:"p17b", t:"08:10", name:"Estación Invalides · RER C", cat:"transport", prio:"P1",
          lat:48.8620, lng:2.3145, addr:"Estación Invalides, RER C, 75007 París",
          do:"18 minutos a pie desde el hotel, cruzando el Pont de la Concorde. Misma línea RER C hacia Versalles.",
          pend:["ANDÉN Y NOMBRE DE MISIÓN DEL TREN: verificar en el panel. En el RER C hay que fijarse en el código de cuatro letras del tren y en que el destino sea VERSAILLES CHÂTEAU–RIVE GAUCHE, no Versailles-Chantiers ni Versailles Rive Droite.",
                "Frecuencia y duración exactas del trayecto: DATO PENDIENTE"] },
        { id:"p17c", t:"09:20", name:"Versailles Château–Rive Gauche", cat:"transport", prio:"P1",
          lat:48.7950, lng:2.1330, addr:"Estación Versailles Château–Rive Gauche",
          do:"Salir de la estación y caminar unos 10 minutos hasta la Place d'Armes. Está señalizado y la mayoría de la gente va al mismo sitio." },
        { id:"p17d", t:"09:30", name:"Place d'Armes · acceso al Palacio", cat:"transport", prio:"P1", res:"r_versalles",
          lat:48.8049, lng:2.1204, addr:"Place d'Armes, 78000 Versailles",
          do:"Con el Passport, el acceso al Palacio es por la Entrada A. Control de seguridad.",
          pend:["Confirmar entrada exacta asignada en el comprobante"] },
        { id:"p17e", t:"10:00", end:"12:30", name:"Palacio de Versalles", cat:"sight", prio:"P1", res:"r_versalles",
          lat:48.8049, lng:2.1204, addr:"Château de Versailles",
          what:"El palacio que Luis XIV convirtió en sede del gobierno de Francia en 1682, para tener a la nobleza vigilada bajo su mismo techo.",
          see:"La Galería de los Espejos (73 metros, 357 espejos), los Grandes Apartamentos y la Capilla Real.",
          do:"El Passport incluye Palacio, Jardines, Trianon y Hameau de la Reine.",
          fact:"Aquí se firmó el Tratado de Versalles en 1919, en la misma Galería de los Espejos." },
        { id:"p17f", t:"12:35", end:"13:55", name:"Jardines de Versalles", cat:"sight", prio:"P2",
          lat:48.8045, lng:2.1180, addr:"Jardins du Château de Versailles",
          what:"800 hectáreas diseñadas por Le Nôtre, con 55 fuentes y 372 estatuas.",
          do:"Bajar por el eje central hasta el Gran Canal.",
          pend:["Horario de la Flotilla (barcas del Gran Canal) y de los espectáculos de fuentes: DATO PENDIENTE. Este es el único dato interno de Versalles sin confirmar."] },
        { id:"p17g", t:"14:00", name:"Comida en Versalles", cat:"food", prio:"P3",
          lat:48.8045, lng:2.1180, addr:"Dominio de Versalles",
          pend:["Restaurante: DATO PENDIENTE"] },
        { id:"p17h", t:"15:00", end:"16:45", name:"Trianon y Hameau de la Reine", cat:"sight", prio:"P3", flex:true,
          lat:48.8150, lng:2.1090, addr:"Domaine de Trianon, Versailles",
          what:"El Gran Trianon, el Pequeño Trianon y la aldea rústica que María Antonieta se hizo construir para escapar de la corte.",
          do:"Está lejos: hay tren turístico de pago o 25–30 minutos a pie desde el Palacio. Si van cansados, esta es la parada que se sacrifica." },
        { id:"p17i", t:"17:30", name:"Regreso a París", cat:"transport", prio:"P1",
          lat:48.7950, lng:2.1330, addr:"Versailles Château–Rive Gauche",
          do:"Mismo RER C en sentido contrario, dirección París." },
        { id:"p17j", t:"20:30", name:"Cena especial", cat:"food", prio:"P2",
          addr:"Por confirmar",
          what:"La cena importante del viaje en París.",
          pend:["SIN CERRAR. Candidato registrado: Joséphine Chez Dumonet. Requiere reserva con antelación. Decidir antes de viajar."] },
        { id:"p17k", t:"23:30", name:"Hotel · preparar maletas", cat:"hotel", prio:"P1",
          lat:48.8664, lng:2.3268, addr:"Meliá Paris Vendôme, 8 Rue Cambon, 75001 París", do:"Mañana es día de aeropuerto." }
      ]
    },

    {
      id: "d18", city: "par", date: "2026-09-18", weekday: "Viernes", type: "transfer",
      concept: "París → Mérida",
      flight: "f3", wake: "05:15", depart: "06:00",
      note: "Horas calculadas sobre un vuelo a las 10:00 sin confirmar. Tres horas de antelación por ser vuelo intercontinental con control de pasaportes.",
      stops: [
        { id:"p18a", t:"06:00", name:"Salida del hotel", cat:"hotel", prio:"P1", lat:48.8664, lng:2.3268, addr:"Meliá Paris Vendôme, 8 Rue Cambon, 75001 París",
          do:"Check-out antes de las 12:00, pero hoy salimos mucho antes. Taxi pedido la noche anterior.",
          pend:["Hora calculada sobre un vuelo a las 10:00 SIN CONFIRMAR. Si la hora del vuelo cambia, esta hora cambia."] },
        { id:"p18b", t:"07:00", name:"Charles de Gaulle", cat:"transport", prio:"P1",
          lat:49.0097, lng:2.5479, addr:"Aeropuerto Charles de Gaulle (CDG)",
          do:"Facturación, control de seguridad y control de pasaportes (salida del espacio Schengen: añade tiempo).",
          pend:["Terminal: DATO PENDIENTE", "Puerta de embarque: VERIFICAR EL DÍA DEL VUELO"] },
        { id:"p18c", t:"10:00", name:"Vuelo de regreso a Mérida", cat:"flight", prio:"P1",
          addr:"Vuelo por confirmar",
          pend:["Aerolínea, número de vuelo, hora de salida y escalas: DATO PENDIENTE"] }
      ]
    }
  ],

  /* --------------------------------------------------- TRAMOS VERIFICADOS
     Solo los tramos cuya ruta está confirmada por una decisión tuya.
     El resto se calcula automáticamente como caminata estimada.
     Clave: "idOrigen>idDestino"
  --------------------------------------------------------------------- */
  legs: {
    "m09a>m09b": { mode:"taxi", dur:35, dist:"14 km",
      steps:["Taxi pedido la noche anterior o pedido en recepción.","Tarifa fija al aeropuerto desde el centro de Madrid: 33 € (revisar tarifa vigente).","Pedir Terminal 4 (T4), no T4S."],
      note:"Salida del hotel 07:45. Es la hora acordada y no debe moverse." },

    "s12f>s12g": { mode:"tren", dur:20, dist:"40 km",
      steps:["Desde el Hotel C, caminar 2 minutos a la Estación Central (Stockholm Centralstation).","Buscar la terminal del ARLANDA EXPRESS, señalizada dentro de la estación.","Sale cada 10–15 minutos. Trayecto de 20 minutos sin paradas.","Bajar en Arlanda: hay dos estaciones (Norra para T2, Södra para T4/T5). Confirmar la terminal de SAS antes de bajar."],
      note:"Alternativa: bus Flygbussarna desde Cityterminalen, 45 min, más barato." },

    "p15a>p15b": { mode:"taxi", dur:20, dist:"por definir",
      steps:["Taxi desde el hotel hasta la estación Charles de Gaulle–Étoile.","Es la ruta que decidimos: evita transbordos con el cansancio de las 07:30."],
      note:"Depende del hotel definitivo de París." },

    "p15b>p15c": { mode:"rer", line:"RER A", dir:"Marne-la-Vallée–Chessy", dur:40, dist:"32 km",
      steps:["Entrar a la estación Auber y seguir los carteles del RER A.","En el andén, mirar la pantalla: el destino debe decir MARNE-LA-VALLÉE–CHESSY. La línea A se bifurca y no todos los trenes llegan.","Tomar el RER A en dirección este.","Bajar en la estación final: MARNE-LA-VALLÉE–CHESSY.","Salir de la estación: la entrada de los parques está a 3 minutos a pie, de frente."],
      note:"Verificar el andén en el panel. El billete de metro sencillo NO sirve: hace falta billete de zona hasta Marne-la-Vallée." },

    "p15h>p15i": { mode:"rer", line:"RER A", dir:"hacia París", dur:45, dist:"32 km",
      steps:["Volver a la estación Marne-la-Vallée–Chessy.","Tomar el RER A en dirección oeste (destinos: Poissy, Cergy o Saint-Germain-en-Laye).","Bajar en AUBER.","Desde Auber, 8 minutos a pie hasta Rue Cambon."],
      note:"CRÍTICO: verificar la hora del último tren el mismo día, en la estación." },

    "p17c>p17d": { mode:"a pie", dur:10, dist:"800 m",
      steps:["Salir de la estación Versailles Château–Rive Gauche.","Seguir la Avenue de Paris o la Avenue de Sceaux, siguiendo al resto de visitantes.","La Place d'Armes y la verja dorada del Palacio quedan de frente."],
      note:"Tiempo real de caminata reportado, no estimado por coordenadas: la estación queda más cerca de lo que sugiere la línea recta." },

    "p17b>p17c": { mode:"rer", line:"RER C", dir:"Versailles Château–Rive Gauche", dur:35, dist:"20 km",
      steps:["Entrar en la estación Invalides, línea RER C.","En el panel, buscar un tren cuyo destino sea VERSAILLES CHÂTEAU–RIVE GAUCHE. No confundir con Versailles-Chantiers ni con Versailles Rive Droite: son otras estaciones y quedan más lejos del Palacio.","Los trenes del RER C llevan un código de cuatro letras. Los que van a Versalles Château empiezan por V. Confirmar en el panel el mismo día.","Bajar en la estación final: Versailles Château–Rive Gauche.","Salir de la estación y caminar unos 10 minutos hasta la Place d'Armes, siguiendo la avenida principal."],
      note:"Ruta acordada. Verificar frecuencia el día anterior: los fines de semana y festivos cambia." },

    "p14a>p14b": { mode:"taxi", dur:20, dist:"4,5 km",
      steps:["Taxi desde la puerta del hotel, en Rue Cambon.","Destino: Pont de Bir-Hakeim, lado 15e.","A las 07:00 de un lunes el tráfico todavía es ligero: 20 minutos es realista."],
      note:"ALTERNATIVA EN METRO (~30 min): caminar 4 min a Concorde, línea 1 dirección La Défense hasta Charles de Gaulle–Étoile, cambiar a línea 6 dirección Nation y bajar en Bir-Hakeim. Verificar andenes en el panel. Con la sesión a las 08:00 en punto, el taxi es la opción segura." },

    "p15a>p15b": { mode:"a pie + RER", dur:12, dist:"600 m a pie",
      steps:["Caminar unos 8 minutos desde Rue Cambon hasta la estación AUBER.","Auber está en la línea RER A: no hace falta taxi ni transbordo previo."],
      note:"CAMBIO RESPECTO AL PLAN PRELIMINAR: la ruta anterior era taxi hasta Charles de Gaulle–Étoile. Con el hotel en Rue Cambon, Auber queda a pie y también es RER A directo. Si prefieres el taxi, dímelo y lo revierto." },

    "p17a>p17b": { mode:"a pie", dur:18, dist:"1,3 km",
      steps:["Caminar desde Rue Cambon hacia Place de la Concorde.","Cruzar el Pont de la Concorde.","Seguir por Quai d'Orsay hasta la estación INVALIDES (RER C)."],
      note:"CAMBIO RESPECTO AL PLAN PRELIMINAR: la ruta anterior salía de Pont de l'Alma, que queda a 2,5 km del hotel. Invalides está a 18 minutos a pie y es la misma línea RER C hacia Versailles Château–Rive Gauche. Si prefieres Pont de l'Alma, dímelo." },

    "p14b>p14c": { mode:"en el sitio", dur:0,
      steps:["Ya estás en el punto de encuentro. Espera junto a la estatua verde, en medio del puente."] },

    "p17i>p17j": { mode:"rer", line:"RER C", dir:"hacia París", dur:35, dist:"20 km",
      steps:["Volver a Versailles Château–Rive Gauche.","Tomar el RER C en dirección París.","Bajar en Invalides y caminar 18 minutos al hotel, o bajar en Musée d'Orsay si prefieres cenar por Saint-Germain."] }
  }
};
